### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by YehyeokBang** [Network-office/Network-office-BE#1]
## 내용
> 프로젝트 초기 설정 후 작업 환경을 공유합니다.

## 할 일
- [x] 작업 컨벤션 지정
- [x] 필요 의존성 선택
- [x] 프로젝트 생성

**Comment by YehyeokBang** [comment]
# 대면 회의 결과

> 2024년 8월 22일 백엔드 파트 대면 회의를 통해 정해진 기본 양식입니다.

## 프로젝트 예상 구조

```
├── domain1 // 멤버, 게시글 등
├── domain2
│    ├── controller
│    ├── service
│    ├── dto
│    ├── domain
│    └── repository
├── global // 예시
│    ├── config
│    ├── auth
│    ├── logging
│    ├── annotation
│    └── error, exception
└── XXXApplication.java
```

각 주제(domain)와 전역에서 사용될 것들을 나누는 형태로 시작되며, 주제 내부에서는 계층형 아키텍처를 사용할 예정입니다.

## 초기 브랜치 전략

```
└── main // 절대 안정
     └── develop // 새로운 기능 추가 및 테스트
           ├── {키워드}/#이슈번호
           ├── {키워드}/#이슈번호
           ├── {키워드}/#이슈번호
           ├── {키워드}/#이슈번호
                   ...
           └── {키워드}/#이슈번호
```
### 사용 예시
- `main` 브랜치는 실제로 릴리즈 가능한 작업만 푸시할 수 있습니다.
- `develop` 브랜치에는 여러 기능이 추가될 수 있으며, `main` 브랜치로 푸시되기 전 여러 기능 추가 및 테스트가 진행됩니다.
- `{키워드}/#이슈번호` 브랜치는 `feat/#2`, `fix/#5`, `test/#11`과 같은 형태로 사용되며 해당 형태의 브랜치는 최소 `develop` 브랜치에서 시작되어야 합니다. `{키워드}/#이슈번호` 브랜치 내부적으로 중첩히여 생성 가능합니다.

## 이렇게 협업해요!
- 긍정의 언어로 대화해요.
- 분업 대신 협업해요.
- 우리는 설득하거나 설득 당해야만 해요.
- 지각은 안돼요.
- 하나의 PR에는 `하나 이상의 이유`가 있어야 해요.
- 되도록 먼저 자신의 상황을 공유해요.
- 질문은 두려워 하지 말아요.

**Comment by YehyeokBang** [comment]
# 데이터베이스

> 채팅을 제외한 회원, 모임 등의 데이터를 저장할 데이터베이스를 결정합니다.

## 고민
- `MySQL` : 대중적인 RDBMS(참고 자료가 많고 안정적), 모든 팀원이 사용한 경험이 있습니다.
- `PostgreSQL` : 완벽한 ACID 지원, 특히 복잡한 사용 사례에서 인기가 높아지고 있습니다.
- `기타` : 다른 데이터베이스를 고려하신다면 말씀해주세요!

의견을 말씀해주세요! @djdongjae 

## 기타

기본적으로 빠른 개발을 위해 Spring Data JPA를 사용할 계획입니다.

**Comment by djdongjae** [comment]
# 데이터베이스

> 채팅을 제외한 회원, 모임 등의 데이터를 저장할 데이터베이스를 결정합니다.

## 고민
- 추가적으로 `MariaDB` 또한 고려할 수 있을 것으로 보입니다. 

## 근거
- 일반적으로 `PostgreSQL`은 대규모 데이터베이스와 복잡한 쿼리에 대해 높은 성능을 보이며, `MariaDB`는 단순한 읽기/쓰기 작업에 대해 좋은 성능을 보이는데 저희 서비스 특성상 복잡한 쿼리보다는 단순 읽기 작업이 훨씬 많을 것 같기 때문입니다.
- `MariaDB`는 `MySQL`과의 호환성을 유지하면서 기능을 개선한 데이터베이스라는 점에서 `MySQL`과 비슷한 문법, 데이터 유형 및 인터페이스를 제공하여 기존 `MySQL`에 익숙한 저희가 쉽게 익힐 수 있을 것으로 보입니다.

## 결론
* 다만 아직 기능이 확정되지 않은 개발 초기 단계에서는 다양한 시나리오를 염두하고 간단한 테스트를 통해 데이터베이스를 결정하는 것도 좋은 방법일 것 같습니다.
* 추가적으로 데이터베이스 [선정 과정 및 기준](https://github.com/djdongjae/TIL/blob/main/db/db_choose.md)에 대해 간단히 정리해 보았습니다.

**Comment by YehyeokBang** [comment]
## 기타

좋은 방법인 것 같습니다.

추가적으로 저희 서비스 특성 상(채팅을 제외한) 조회가 더 많을 것 같다는 의견에 동의합니다. [테스트 참고 블로그](https://a-platform.tistory.com/m/121)를 살펴보면, `PostgreSQL`의 조회 성능이 미묘하게 낮은 것을 볼 수 있습니다.

`MySQL`과 `MariaDB` 중에서 선택하는 것도 좋은 과정인 것 같습니다!

**Comment by sss4920** [comment]
# 데이터베이스

> MySQL과 MariaDB 중에서 선택하는 것도 좋은 과정인 것 같습니다!

위의 근거들에 동의함에 따라 저도 이 중에서 선택하는 것이 좋을 것 같다고 생각합니다.

## 의견 제시
- 많은 레퍼런스를 참조하여 효율적이고 빠른 개발을 위해서라면 MySQL을 선택하고 필요에 따라 MariaDB로 이전하는 것은 어떻게 생각하시나요? 

## 근거
- MariaDB는 MySQL과의 이전 버전 호환성을 제공하도록 설계되었습니다. 따라서 MySQL용으로 작성된 애플리케이션 및 스크립트는 큰 변경 없이 MariaDB에서 작동합니다. 따라서 이전하는데에 있어서 리소스가 크지않을 것이라고 생각합니다.
- 성능 비교로는 MySQL 8.0이 MariaDB 10.3 버전보다 초당 더 많은 쿼리를 처리할 수 있다고 합니다. 
MariaDB가 꾸준히 발전해왔다지만 저희가 사용할 MySQL 버전에 따라 다를 것이라고 생각되기 때문에 
- 적은 db이전에 대한 리소스 + 성능 차이가 크게 없으며 나중에 DB 마이그레이션 작업 또한 좋은 경험이 될 수 있을 것이라고 생각되는데 어떻게 생각하시나용?

## 참고 레퍼런스
- https://aws.amazon.com/ko/compare/the-difference-between-mariadb-vs-mysql/

**Comment by YehyeokBang** [comment]
# 의견

> 의견을 종합해봤을 때 `MySQL`을 사용하는 것이 좋은 출발이 될 것 같아요.

`커뮤니티의 크기`, `실제 작동하는 것을 비교하지 않는 이상 큰 차이를 체감하기 어려울 수 있음`, `팀원 모두 익숙함`을 이유로 `MySQL`을 선택하는 것이 좋을 것 같은데 어떻게 생각하시나요?

 찬성하신다면 👍 이모지를 눌러주시고, 다른 의견이 있으신 경우 답변 부탁드립니다!

## 기타

> 추가적인 의존성에 대해 고민해봐요.

저는 모두가 활용한 경험이 있고, 많은 프로젝트에서 사용되는 `lombok`을 이번에도 사용하면 좋을 것 같아요.

**Comment by YehyeokBang** [comment]
# 의견

> 로컬 및 테스트 환경에서는 h2 데이터베이스 환경을 사용하기는 어때요?

로컬까지는 아니더라도 동일한 환경에서 테스트 코드가 작동하도록 메모리 환경에서 h2 데이터베이스를 사용하는 것은 어떻게 생각하시나요?
@sss4920, @djdongjae

**Comment by sss4920** [comment]
# 의견
> 로컬 및 테스트 환경에서는 h2 데이터베이스 환경을 사용하기는 어때요?

저도 h2환경을 자주 사용해보니 편의성 면에서도 좋아 동의합니다.

# 고민 
하지만 MySQL과 h2가 호환이 안되는 부분들이 몇가지 있는 걸로 알고 있습니다. 
예를 들면 Orders라는 테이블을 만들었다가 h2에서 예약어로 인식한다든가 문제가 있었던 사례가 있었습니다.

## 고민에 대한 의견
h2와 연동을 고려해서 엔티티 작성을 고려할지? 아니면 test configuration을 따로 지정해줄지도 고려해보면 위와 같은 `동일한 환경` 테스트 작동 환경을 구축할 수 있을 것 같아 고민해보면 좋을 것 같습니다.

**Comment by sss4920** [comment]
# 필요 의존성 요청
> 스프링 시큐리티 의존성 도입에 대해서는 어떻게 생각하시나요?

# 의견
저희 서비스의 세션관리 및 인증, 인가 작업에 있어서 필요한 필터들만 적절히 사용하게 된다면 좋은 영향을 가질 수 있을 것 같아서 사용하는 것이 어떨까 제안해봅니다.

- 그 외에 잘못사용했을 때의 단점등을 아래와 같이 블로그에 작성해봤습니다.
- https://blog.naver.com/sss4920/223560182445

**Comment by YehyeokBang** [comment]
> 하지만 MySQL과 h2가 호환이 안되는 부분들이 몇가지 있는 걸로 알고 있습니다.
> 예를 들면 Orders라는 테이블을 만들었다가 h2에서 예약어로 인식한다든가 문제가 있었던 사례가 있었습니다.

Spring Data JPA를 사용하면 대부분의 데이터베이스 관련 작업이 추상화되기 때문에, MySQL과 H2 같은 데이터베이스 간의 호환성 문제는 많이 줄어든다고 생각해요. 하지만 아래의 문제는 확인해볼 필요가 있을 것 같아요.

- `예약어 충돌` : 예약어를 테이블 이름으로 사용할 경우, H2나 MySQL에서 충돌이 발생할 수 있기 때문에 예약어를 피해야 해요. 굳이 예약어를 사용해야 한다면, 테이블 이름에 백틱(\``)이나 큰따옴표("`)를 사용해 감싸는 방법이나 우리만의 컨벤션을 지정하는 것도 좋은 방법일 것 같아요. 이런 문제 해결의 중점은 일관성인 것 같아요!
- `데이터베이스 고유 기능` : MySQL과 H2는 각각의 고유한 기능과 SQL 문법이 있다고 알고 있어요. Spring Data JPA는 이런 차이점을 최소화해주지만, 일부 기능이나 고급 쿼리는 데이터베이스별로 다르게 동작할 수 있어요. 따라서 배포 전 `main` 브랜치로 병합되기 전에는 MySQL로도 테스트를 진행하는 것으로 보완하면 좋을 것 같아요.

## 결론

실제 릴리즈해야 하는 경우 MySQL 데이터베이스를 활용한 테스트가 충분히 이루어지도록 하고, 로컬 및 테스트 환경에서는 `일관성`, `편의성`을 위해 H2 데이터베이스를 쓰는 방향도 좋을 것 같아요. 예약어 충돌의 경우에는 미리 컨벤션을 지정하는 것이 좋아보여요.

Spring Data JPA를 사용하기 때문에 비교적 간단한 로직에서 큰 차이는 없을 수 있어요. 다만, 고급 함수 기능이나 지원하는 타입의 차이가 있을 수 있으니 실제 배포 전 확인하는 과정이 필요할 것 같아요.

**Comment by YehyeokBang** [comment]
> * 그 외에 잘못사용했을 때의 단점등을 아래와 같이 블로그에 작성해봤습니다.
> * https://blog.naver.com/sss4920/223560182445

읽어봤는데 좋은 것 같습니다. 아무래도 Spring 생테계에서 Spring Security는 표준에 가까운 프레임워크이기 때문에 이 부분에서 이점이 많을 것입니다. 물론 말씀하신 것처럼 필요하지 않지만 가져다 쓰거나, 이유를 모르고 사용한다면 문제가 될 것 같습니다.

필요한 것들만 부분적으로 학습 후 적용한다면, 비교적 쉽게 보안성을 높일 수 있고, 유지보수성을 높일 수 있을 것 같습니다!
