### ISSUE TITLE
로그인 기능 구현

### ISSUE THREAD

**Issue by YehyeokBang** [Network-office/Network-office-BE#2]
## 내용

> 로그인 방식에 대한 전체적인 틀을 결정합니다.

## 할 일

- [x] 요구사항 분석
- [x] 여러 로그인 방식 비교
- [x] 로그인 기능 구현

**Comment by YehyeokBang** [comment]
# 내용

> 로그인 기능을 구현하기 전, 최선의 선택을 위해 요구사항을 분석하고 함께 이야기 해보고 싶어요.

# 프론트엔드 파트 요구사항
- `SSR` 환경에서 로컬 스토리지에 접근할 수 없어요. (NextJS를 사용해요.)
- 또한, 로컬 스토리지에 토큰이 있으면 js에서 접근할 수 있다보니 보안에 취약할 수 있어요.
- `MSA-모노레포` 환경을 고려하고 있어요. 서브 도메인끼리 로컬 스토리지, 세션 스토리지를 공유하지 않아요.

# 백엔드 파트 요구사항
- 근거 없는 기술 사용을 지양해요.
- 빠르게 개발하여 눈으로 확인하고 싶은 마음이 있어요.

제가 [분석한 내용](https://velog.io/@hyeok_1212/%EC%96%B4%EB%96%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EB%B0%A9%EC%8B%9D%EC%9D%84-%EC%84%A0%ED%83%9D%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C)을 읽어주시면 좋을 것 같아요!

**Comment by YehyeokBang** [comment]
# 추가 내용

세션 방식과 JWT 방식 모두 악의적인 사용자가 탈취하여 그 사용자인척 할 수 있어요. 하지만, 세션 방식은 서버에서 탈취된 세션 ID를 무력화할 수 있고, JWT 방식은 만료 기한이 다가올 때까지 무력화할 수 없어요.

**Comment by djdongjae** [comment]
# 고민

> 좋은 분석 내용인 것 같습니다! 

* 세션 방식과 JWT 방식 모두 장단점이 있는 것은 분명한 것 같아요. 다만 쿠키를 사용했을 때 악의적인 사용자가 그 사용자인척 할 수 있는 CSRF 공격에 대응하기 위해서는 CSRF 토큰 발급 구현을 고려해야 할 수도 있을 것 같습니다. 
* 공식문서에 따르면 스프링 시큐리티에서 제공하는 CSRF 공격 방지 기능은 `non-browser clients` 즉 SPA에서는 비활성화를 권장하고 있습니다. 
* 이에 대한 구현 방법으로 `Double-Submit-Cookie-Pattern`을 제안해 봅니다. 
* 물론 세션 방식을 활용해서 세션 ID가 탈취됐을 때 위험도가 현저히 낮은 정도라면 아마 안해도 될지도...?

<br>

<img width="1091" alt="Screenshot 2024-08-26 at 8 48 46 AM" src="https://github.com/user-attachments/assets/0b87f5b0-8f58-41b4-a3c5-9b75c4dc334c">

**Comment by YehyeokBang** [comment]
# 의견

> 의견 감사합니다!

말씀하신 것처럼 세션 방식이라도 별도의 구현이 없다면 악의적인 사용자가 탈취하여 사용하는 상황(만료기간 전까지)을 막을 수 없어요. 일정 시간동안 요청이 없는 경우 강제로 무력화 한다거나, 하나의 기기에서만 로그인을 할 수 있도록 구현하는 방식을 통해 부족한 부분을 보완할 수 있을 것 같아요!

`CSRF`에 대해서 더 알아봐야겠네요. 감사합니다!

**Comment by YehyeokBang** [comment]
## 의견

> 사용자 입장에서 회원가입과 관련된 내용 정리 및 제안입니다.

[추가 제안](https://velog.io/@hyeok_1212/%EC%96%B4%EB%96%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EB%B0%A9%EC%8B%9D%EC%9D%84-%EC%84%A0%ED%83%9D%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C-2)을 읽어주시면 좋을 것 같아요!

## 내용

> 팀원 분들의 의견을 듣고 싶어요! (일반 회원가입 및 OAuth 2.0, 회원 관리 방법 등)

**Comment by ienrum** [comment]
# 의견

> 블로그 글 잘 봤습니다!

저는 사용자 관점에서, Oauth 2.0 이 더 나은 방법인것 같습니다.

블로그 글중에 `여러 사용자가 다른 사람인척 특정 분위기를 조성할수있다` 이부분에 동의하고,
휴대폰인증 방법 또한 좋은 방법인것 같습니다. ( 기획과 비슷한 당근도 요방법을 쓰는것같네요 ).

**Comment by djdongjae** [comment]
# 의견

> 블로그 글 너무 잘 봤습니당🤗

* 저는 가장 먼저 저희 팀이 논의해야 할 사항 중에 하나가 **타켓 선정**이라고 생각합니다. 연령, 지역, 소속 등 타켓을 명확히 선정해야 이에 따른 회원가입 시 인증 방식이 달라질 것 같습니다. 
* 소셜로그인 관련해서는 저희 서비스가 타겟이 제한된 서비스이다 보니 우선 일반로그인으로 진행하여 타겟 인증 절차를 공고히 한 다음에, 추후 소셜로그인 연동 기능을 도입하는 게 가장 좋은 방식이라고 생각합니다!

**Comment by JuJangGwon** [comment]
# 의견 

> 오호라 여러 방면으로 꼼꼼히 정리해주셨군요? 블로그 글 잘봤습니다! 😁

저는 먼저 본론부터 얘기하자면  통합 회원관리 부분이 좋다고 생각됩니다.
예혁님이 블로그에 작성하신 고유한 식별 정보를 이메일로 구분했을 때 여러 이메일을 사용(sns에 연결)중인 사용자는 동일한 사용자로 인식하기 어려운 문제는 휴대폰 인증을 통해 해소 시킬 수 있을거 같습니다. 여러 이메일을 쓰는 사람은 많아도, 여러 휴대폰 번호를 쓰는 사람은 적으니까요 :)

후후 그래서 정확히 제가 생각한  휴대폰 인증을 통한 식별 정보 플로우는 이렇습니다. 
* 자체 회원가입 플로우에 휴대폰 인증을 필수적으로 구성한다 -> 인증 성공시 해당 휴대폰 번호로 가입된 SNS 계정이 있다면 연결 그렇지 않다면 회원가입 개인정보 입력 단계 진행 
* 새로운 SNS계정이 소셜 로그인을 시도한다 -> 휴대폰 인증을 한다 -> 인증 성공시 해당 휴대폰 번호로 가입된 계정이 있다면 자동적으로 해당 계정을 SNS 연결해준다. 만약 가입된 계정이 없다면 회원가입 플로우 진행  

이렇게 휴대폰 번호 인증 방식을 사용한다면 블로그에 작성하신 ...
*  한 명의 사용자가 다수의 계정을 만드는 것을 억제하여 계정에 책임감을 갖게 하고, 각 계정마다 신뢰도를 높이는 것이 중요하다고 생각해요.
*  SNS 폐쇠, SNS 계정 해킹으로 인한 문제 

이 부분들도 해결 할 수 있다고 생각됩니다.

**Comment by YehyeokBang** [comment]
우선 팀원 분들의 의견 잘 들었습니다. 감사합니다.

# 의견

> 휴대폰 인증의 단점은 `가격 부담`과 `여전히 사용자를 (항상 유일하게 식별하고) 통합하기 위한 수단이 될 수 없다는 것`입니다.

- 휴대폰 인증은 `건당 n원` 형식으로 요금이 부과되는 기능 중 하나입니다. 따라서 유지 부담이 커질 수 있습니다. (이메일 인증은 무료로 구성할 수 있습니다.)
- 소셜 로그인의 장점은 빠르게 가입할 수 있고, 민감한 정보를 적게 입력하는 것입니다. 하지만 소셜 로그인마다 휴대폰 인증을 추가한다면, 일반 로그인과 큰 차이가 없는 플로우를 경험하게 될 것 같습니다.
- 휴대폰 번호도 변경될 수 있습니다. 만약 이전 번호를 기준으로 가입된 계정이 있을 때 잘못된 계정 통합으로 이루어질 수 있습니다. 번호 인증을 통해 그 순간에 자신이 맞다고는 볼 수 있지만, 이전 시점에 A 번호로 가입한 사람과 추후에 A 번호를 통해 다른 SNS 계정으로 가입한 사람을 동일 인물이라고 보기엔 위험하다고 보여집니다.

즉, 이메일, 전화번호, 기타(주민등록번호는 수집 불가, 심지어 같은 주민등록번호를 가진 사람이 있을 수 있습니다.) 등등 다양한 경로로 가입하는 사용자를 정확히 식별하여 같은 사람끼리 그룹핑 할 수 있는 방식이 꽤 어려울 것으로 보여집니다.

## 제안

저는 동재님 의견처럼 초반 타겟(특정 학교, 동네 등)을 설정한다면 그 인증(합격증, 위치 등)을 받는 것이 중요하다고 생각해요. 

하지만 일반 회원가입 자체에 타겟 인증을 도입하면 가입 시 이탈이 자주 발생하게 될 것 같습니다. 관리자가 직접 인증하는 것이라면 승인 전까지 가입을 할 수 없을 것 같아요.

따라서, 저는 `소셜 로그인`을 통해 빠르게 가입하는 것으로 유입을 늘리고, 타겟 인증이 필요하지 않은 콘텐츠(간단한 게시글 조회 등)를 볼 수 있게 하며, 이후 타겟 인증을 진행할 수 있게 하는 것이 좋을 것 같다고 생각했습니다. 어떻게 생각하시나요? (추후 타겟 인증은 에브리 타임의 가입 방식을 참고했습니다.) @JuJangGwon @djdongjae @ienrum @sss4920 @khj0426 

추가적으로 비용 문제를 고려하여 이메일로 최대한 같은 회원임을 인식하는 장치로 사용하고, 만약 이미 다른 SNS 계정으로 가입된(이미 이메일이 존재하는) 경우라면 회원가입을 중단하고 다시 로그인하게 하는 것도 좋을 것 같습니다. 가장 자주 사용되는 네이버, 카카오, 구글 중에서 1~2개만 고른다면, 또는 우선적으로 카카오 로그인먼저 제안하고 다른 SNS 계정으로 로그인 탭을 만드는 등 디자인을 통해 한쪽 SNS 계정으로 가입하도록 유도할 수도 있을 것 같습니다. (다중 SNS 계정으로 하나의 서비스 계정이 연결되어 있는 것에서 얻을 수 있는 이점이 크지 않다고 판단했습니다.)

> 타켓 인증 : 우리가 서비스를 제공하려는 타겟이 맞는 지 사용자가 인증하는 것을 의미해요. 예를 들어, 부천시 거주자를 위한 서비스를 사용하기 위해 사용자가 부천시 거주를 증빙하는 자료를 제출하여 승인받는 것을 말해요.

## 추가 제안

> 가능성을 검토해보고 말씀드릴게요!

사용자가 생성된 인증번호를 휴대전화 문자로 보내게 하여 인증하는 방식은 어떨까요?

**Comment by khj0426** [comment]
# 의견

> 블로그 글 잘 보았습니다.. 정말 꼼꼼히 정리하셨네요 👍 저도 개인적으로 로컬스토리지보단 보안적인 이유, 그리고 코드의 복잡성이 증가한다는 점에서 쿠키를 더 선호하는 편인데, 쿠키 기반의 설명이 잘되어있어서 좋았어요!

저는 서비스 접근성 하나 만으로 소셜 로그인을 도입하는 게 좋다고 생각하는데 궁극적으로 통합회원관리로 가는게 맞다고 생각해요!

휴대폰 인증은 비용만 괜찮다면? 도입해도 좋지 않을까 생각입니당

**Comment by YehyeokBang** [comment]
csrf 공격 방지를 위한 설정 전까지 open 하겠습니다!
