### ISSUE TITLE
API 문서화 도구 선택

### ISSUE THREAD

**Issue by YehyeokBang** [Network-office/Network-office-BE#4]
## 내용

> API 문서화를 위해 사용할 도구를 비교하고 선택합니다.

## 할 일

- [x] API 문서화 도구 비교
- [x] API 문서화 도구 선택

**Comment by YehyeokBang** [comment]
## 요약

> Swagger를 제안합니다.

## 내용

불특정 다수 또는 외부로 제공할 API가 아니기 때문에 우리 팀에게 API 문서화의 목적은 더 나은 개발을 위해 API 명세서를 만드는 것입니다. 따라서 모든 팀원들이 사용해본 이력이 있고, 구현이 비교적 어렵지 않은 `Swagger`를 사용하는 것이 좋다고 생각했습니다.

## Swagger 단점

Swagger를 사용해본 백엔드 입장에서 프로덕션 코드(Controller Layer)가 더러워지고 가독성이 나빠진다는 단점이 있습니다. 추가적으로 상용 코드에 Swagger의 어노테이션이 붙기 때문에 변경에 취약한 점을 보여줍니다.

## 해결 방안

API 명세 관련 코드를 interface로 분리하여 사용하는 방안을 제시합니다.

```java
@Tag(name = "Member Api", description = "멤버 관련 API")
public interface MemberApiDocs {

    @Operation(
            summary = "로그인",
            description = "이메일과 비밀번호를 통해 로그인합니다."
    )
    @ApiResponses(value = {
            @ApiResponse(
                    responseCode = "200",
                    description = "정상적으로 로그인 됨"
            ),
            @ApiResponse(
                    responseCode = "500",
                    description = "로그인에 문제가 생김"
            ),
    })
    ResponseEntity<Void> login(@RequestBody MemberEmailAndPassword request);

    @Operation(
            summary = "로그아웃",
            description = "로그아웃을 진행합니다."
    )
    ResponseEntity<Void> logout();
}
```

```java
@RestController
@RequiredArgsConstructor
public class MemberController implements MemberApiDocs {
    ...
}
```

위와 같이 interface에 명세 관련 코드를 모두 작성하고 이를 구현하도록 하는 방안입니다. 

이 방식의 장점은 실제 상용 코드에 Swagger 관련 코드 침범이 매우 적다는 것입니다. (implements만 지우면 쉽게 의존을 제거할 수 있어요.)

단점으로는, interface를 interface답게 사용하지 못해요. 추상화를 위해 interface를 사용하는데 이 방식으로 만들어진 interface는 사실 API 문서화를 위해 구현 내용(어노테이션들)이 포함되어 있습니다.

저는 `interface`의 일반적인 형태를 포기하고 `가독성`, `유지보수성`을 얻으면서 API 명세서를 쉽게 만들 수 있다는 부분에서 제안드립니다. 다만, 이러한 패턴을 `팀원 모두가 일관성`있게 사용해야만 큰 문제 없이 장점들을 누릴 수 있을 것 같습니다.

## 기타

혹시 `RestDocs`나 `Postman` 등 다른 도구를 API 문서화 도구로 사용해본 경험이 있으신가요?

**Comment by sss4920** [comment]
> API 명세 관련 코드를 interface로 분리하여 사용하는 방안을 제시합니다.
> 프로덕션 코드(Controller Layer)가 더러워지고 가독성이 나빠진다는 단점

좋은 해결방안인 것 같습니다..! 위와 같은 단점에 매우 공감을 하고 있었는데 이런식으로 interface로 분리한다는 생각을 미처 못했던 것 같네요.☺️

> 추상화를 위해 interface를 사용하는데 이 방식으로 만들어진 interface는 사실 API 문서화를 위해 구현 내용(어노테이션들)이 포함되어 있습니다.

이 부분에 대해서는 조금 더 고민해보겠습니다!

## 의견 제시
swagger로 일단 작성을 하고 나중에 어느정도 develop이 완료되고 테스트 코드를 잘 작성해보면서 RestDocs를 도입해보면 어떨까요?

## 근거
RestDocs는 분명 테스트 코드를 강제하여 안정성을 부여한다는 점이 좋다고 생각하지만, 현재 develop 단계에서는 오히려 클라이언트에게 빠르게 개발 명세서를 던져주는 방향이 더 좋을 것 같다고 생각합니다. RestDocs는 테스트 코드를 다 작성하지 않으면 그 기능 자체가 명세서에 올라가지 않는 것으로 알고있기 때문에 현재 도입은 개발 속도를 늦추게 될 가능성이 있다고 생각합니다.

## 기타

> 혹시 RestDocs나 Postman 등 다른 도구를 API 문서화 도구로 사용해본 경험이 있으신가요?

저는 postman과 swagger를 다뤄봤습니다.

**Comment by YehyeokBang** [comment]
## 의견

> develop 단계에서는 오히려 클라이언트에게 빠르게 개발 명세서를 던져주는 방향

이 방향에 공감합니다. 추가로 테스트를 직접 진행해볼 수 있으니 개발 단계에서는 더 좋은 시너지를 낼 것 같습니다.

> RestDocs를 도입해보면 어떨까요?

좋은 것 같습니다. 하지만 변경 시점(또는 추가 시점)은 개발을 진행하면서 필요성을 느낄 때로 맞추면 좋을 것 같습니다!
