### ISSUE TITLE
모임 기능 구현

### ISSUE THREAD

**Issue by sss4920** [Network-office/Network-office-BE#6]
## 내용

> 모임 구현 방식에 대한 전체적인 틀을 결정합니다.

## 할 일

- [x] 요구사항 분석
- [x] 모임 구현 방식 결정
- [x] 모임 기능 구현

**Comment by sss4920** [comment]
> 요구사항 분석
<img width="763" alt="image" src="https://github.com/user-attachments/assets/ca495c89-595f-4939-956b-9c911850000d">
<img width="786" alt="image" src="https://github.com/user-attachments/assets/62be1847-4906-4619-b6be-4f44c307ce6b">


## 모임의 구조
### 모임 대표 정책.
  - 모임 대표는 신청한 유저들의 `승인`과 `거부`를 결정할 수 있다.
    - 승인된 유저는 해당 모임의 `확정된 인원`으로 등록된다.
    - 모임 대표가 거절할 시에는 `거절 사유`를 등록해야한다.
    - `거절된 유저`는 해당 모임에 해당 모임에 들어올 수 없으며, `거절 사유를 확인`할 수 있다. 
  - 모임 대표는 확정된 인원을 `추방 사유`의 등록과 함께`추방`할 수 있다.
  - 모임 대표는 확정된 인원과 신청한 유저들의 `프로필을 확인`할 수 있다.
  - 모임 대표는 해당 모임의 정보를 수정할 수 있다.
  - 모임 대표는 해당 모임을 `파토`낼 수 있다. 파토시에는 `파토 사유`를 등록해야한다.
  - 모임 대표는 해당 모임 신청을 `마감`할 수 있다.

### 모임 신청자 정책.
  - 모임 신청자는 해당 모임에 신청, 관심을 생성할 수 있다.
  - 모임 신청자는 모임 대표의 `프로필을 확인`할 수 있다.
  - 확정된 인원으로 승인되어 들어가면 채팅방에 초대 된다.
  - 해당 모임이 종료되면 리뷰를 남길 수 있다.
  - **모임 신청자는 해당 모임을 `신고사유`의 등록과 함께 `신고`할 수 있다.**
    - **신고당한 모임은 `해당 신고자에게서 분리`되고 `신고접수된 모임`에 등록된다.**
    - **위에서의 `분리`는 그 해당 신고자가 `해당 모임을 조회할 수 없음`을 뜻한다.**
    - **`신고 접수된 모임`은 관리자가 판단 후 `간단한 사유`를 모임 대표와 확정된 인원들에게 `통보한 후 제거` 할 수 있다.**


### 모임 1개에는 여러 개의 `관심`을 받을 수 있다. (유저 1명 당 해당 모임에 1개의 관심을 생성할 수 있다.) 

### 모임 1개에는 종료시에 여러 명의 유저가 후기를 남길 수 있다.
  - `후기`는 `참여자 이름`, `후기`, `평점(1~5)`으로 구성되어있다. 
### 모임 1개에는 생성시에 1개의 `단체 채팅방`이 만들어지며, 초대되어 `확정된 인원`들은 해당 채팅방에 참여할 수 있다.

## 모임 생성
- 모임 생성시에는 1개의 `카테고리`를 설정할 수 있다.(회의에 결정된 방식 - 카테고리는 우리가 정해준 범주에서 선택한다.)
- 모임 생성시에는 1개의 `장소`를 설정할 수 있다. (`지도api에서 필요한 파라미터`를 반영한다.)
- 모임 생성시에는 `예상 활동 시작시간`과 `종료시간`을 설정할 수 있다. 
- 모임 생성시에는 `최대 신청 인원`을 정해놓을 수 있다.
- 모임 생성시에는 `모임 설명`을 기록해놓을 수 있다.

## 모임 수정
- 모임 수정시에는 `모임 설명`, `카테고리`, `장소`, `예상 시작시간`과 `종료시간`, `최대 신청인원`을 `수정`할 수 있다.

## 모임 종료
- 모임 종료에는 `파토`와 `정상 종료`로 나뉜다.
  - 파토시에는 `모임 인원들`에게 파토가 났음을 알리는 `파토사유가 담긴 알림`을 발송한다.
  - `정상 종료`시에는 마감된 모임에 한해 `예상 종료시간`을 넘으면 해당 인원들은 모두 `후기`를 남길 수 있다.

**Comment by sss4920** [comment]
대략적으로 이해한 요구사항을 작성해봤습니다.
추가하거나 수정해야할 사항이 있으면 같이 여기서 논의 해보면 좋을 것 같습니다. ☺️
@JuJangGwon

**Comment by YehyeokBang** [comment]
## 의견

전체적으로 이해하기 쉬웠습니다! 고생하셨어요.

> 모임 대표는 확정된 인원을 추방할 수 있다.

추방도 마찬가지로 사유를 작성하고 볼 수 있다고 적어두면 좋을 것 같아요!

> 평점

소수점은 제거하고 별점과 유사하게 1~5개로 설정하여 피로도를 낮추고 쉽게 작성할 수 있도록 하면 좋을 것 같아요.

> 모임 신고

추가적으로 모임에 대한 신고도 생각해두면 좋을 것 같아요.

**Comment by JuJangGwon** [comment]
## 의견
수정사항은 보이지 않는거같네요 고생많으셨습니다. 👍
추가해볼만 사항이라면..앞서 예혁님이 언급하신 의견 모두 고려해볼만한 좋은 의견들 같네요.  
그밖에도... 

>모임 신청자 정책

모임 신청자 역시 모임 안내 페이지에서 모임 생성자의 프로필도 들어갈 수 있으면 좋을거같네요!
> 모임 종료

모임 종료시 해당 모임 채팅방 종료시점도 한번 의견을 나눠봐야될거같아요!

**Comment by sss4920** [comment]
## 피드백들에 대한 감사
너무 좋은 의견들입니다. 제가 놓친 부분들도 잘 정리해주셨군요! 반영하여 수정해보았습니다.

> 추가적으로 모임에 대한 신고도 생각해두면 좋을 것 같아요. 

이에 매우 공감합니다. 저는 전에 진행했던 프로젝트에서 IOS 정책에서 커뮤니티 어플같은 경우 신고한 게시물을 분리시켜야한다는 이유로 리젝을 당했던 기억이 있습니다.

따라서 신고에 대해서 고민을 해보았고 위와 같이 정리해봤습니다.

## 신고 기능에 대한 의견

> 모임 신청자는 해당 모임을 신고사유의 등록과 함께 신고할 수 있다.
  > 신고당한 모임은 해당 신고자에게서 분리되고 신고접수된 모임에 등록된다.
  > 위에서의 분리는 그 해당 신고자가 해당 모임을 조회할 수 없음을 뜻한다.
  >신고 접수된 모임은 관리자가 판단 후 간단한 사유를 모임 대표와 확정된 인원들에게 통보한 후 제거 할 수 있다.

이정도로 구상을 해보았는데, 어떻게 생각하시나요?
@JuJangGwon @YehyeokBang @djdongjae

**Comment by YehyeokBang** [comment]
좋습니다! 신고된 모임을 어떻게 구별하고 핸들링할지 고민도 해봐야겠네요!
