### ISSUE TITLE
공통 응답 템플릿 추가

### ISSUE THREAD

**Issue by YehyeokBang** [Network-office/Network-office-BE#8]
## 내용

> API 응답 템플릿을 구현하여 항상 일관된 형태의 응답을 받을 수 있도록 합니다.

## 할 일

- [x] 템플릿 구조 결정
- [x] 구현

## 제안

```json
{
    "status": "404",
    "message": "찾을 수 없음",
    "data": "데이터"
}
```

~~위와 같은 형태로 정상 및 예외 응답을 공통적으로 관리하면 어떨까요?~~ 잠시 보류입니다. 아래의 이슈 답글을 확인해주세요!

**Comment by YehyeokBang** [comment]
## 제안

> ResponseBodyAdvice를 구현하여 불필요한 코드를 줄여보는 것은 어떨까요?

`ResponseBodyAdvice`는 서버가 클라이언트에게 응답을 보내기 직전에 그 응답 데이터를 가로채고 변환하는 데 사용돼요. 

**모든 컨트롤러에서 반환하는 응답을 일관되게 처리할 때 유용할 것 같아요.**

이를 이용하면 모든 응답을 일관된 형태로 감쌀 수 있을 것 같아요. 항상 같은 응답 형태를 반환하지만, 각각의 컨트롤러마다 코드를 작성하지 않고 이 코드를 통해 자동으로 감싸서 반환할 수 있도록 (중복 제거) 할 수 있을 것 같아요.

## 참고
- [참고 블로그](https://whalesbob.tistory.com/18)

**Comment by YehyeokBang** [comment]
## 고민

막상 테스트를 해보면서 생각해보니, 공통 응답에 대한 필요성은 백엔드 팀이 개발한 API를 헷갈리지 않고 잘 쓸 수 있는가?에 대한 의문부터 나오는 것 같아요.

우선적으로 프론트 팀과 협의하여 어떤 형식으로 API 응답을 전달 받기를 원하는지 이야기해볼 필요가 있다고 생각해요.

## 예시 
- 응답에서 본문의 데이터만을 활용하기로 결정한다면, 실제 HTTP status code 같은 것은 설정해줄 필요가 없을 수도 있어요.
- 항상 같은 데이터 포맷으로 응답이 오길 바란다면, 성공이나 예외 모두 같은 포맷으로 응답할 수 있어요.
- 성공을 세세하게 나누지 않고 200으로 통일하고 싶어요! (새로운 자원이 생성되는 경우 `201 CREATED`를 응답했어야 하는데 서버가 200 OK를 응답했다. 이때 프론트엔드는 예외 상황으로 처리할 것인가? 아니라면 세세하게 나눌 필요가 있는가?, 이런 류의 고민이 필요할 것 같아요.)

@JuJangGwon @ienrum  @khj0426  @djdongjae @sss4920

**Comment by sss4920** [comment]
> ResponseBodyAdvice는 서버가 클라이언트에게 응답을 보내기 직전에 그 응답 데이터를 가로채고 변환하는 데 사용돼요. 

이렇게 하면 확실히 컨트롤러 단에서 불필요한 공통 response를 만드는 번거로움이 줄어드는군요! 좋은 것 같습니다.

> 우선적으로 프론트 팀과 협의하여 어떤 형식으로 API 응답을 전달 받기를 원하는지 이야기해볼 필요가 있다고 생각해요.

공감합니다. 이에 대해서는 오늘 회의해서 논의해보고 그걸 정리한 내용을 이 이슈에 기록하면 좋을 것 같습니다.

**Comment by YehyeokBang** [comment]
## 회의 결과

> 팀원들의 의견을 종합한 내용이에요.

- **성공**에 대한 상태를 세세하게 나누는 것을 아직까진 불필요하다고 느껴진다.
- 상태코드는 HTTP 응답 본문에 함께 보내주면 좋을 것 같다. (모든 응답은 200이고 body에만 상태코드를 입력하는 것은 불편하다.)
- 데이터 전달을 위한 공통 템플릿은 큰 필요성을 느끼지 못한다. (성공했을 때 메시지는 필요하지 않다. **성공이 중요하다.**) 따라서 body 자체가 바로 사용할 데이터를 추가해도 괜찮다. (또한 스웨거에서도 예상 데이터 형식을 쉽게 볼 수 있지 않을까요? 라는 의견)

즉, API 호출 시 성공은 모두 `200 OK` 상태 코드를 반환하고, 예외만 세분화합니다.
